### ISSUE TITLE
Create Tap Tempo Page

### ISSUE THREAD

**Issue by johnxgaehner** [johnxgaehner/beatmatch-buddy#12]
## Value Statement
As a user of Beatmatch Buddy I want to analyze the tempo of a given song so that can pitch it more easy and faster!

## Description
Tap to the rhythm of the music and receive the calculated tempo/bpm of the song. After adding track title, artist name and record title - you can save the track in your collection.

## Acceptance Criteria
- The bpm will be shown in realtime
- You can add artist name, track name and record title and store all info in your collection

## Complexity
Medium - Large

## Resources
- https://codepen.io/Theavon/pen/dyYeVLY?editors=0110

## Tasks
- [x] Setup Tap Tempo Component
- [x] Write basic markdown
- [x] Calculate tempo out of taps in a given time
- [x] Store result in a state
- [x] Display tempo/state
- [x] Add track infos and store in collection
