### ISSUE TITLE
Create Collection Page

### ISSUE THREAD

**Issue by johnxgaehner** [johnxgaehner/beatmatch-buddy#14]
## Value Statement
As a user of Beatmatch Buddy I want to have a place with my whole collection to scroll through the tracks, filter and compile playlists.

## Description
Save a track on the Analyse Page and it will be shown in your Collection.

## Acceptance Criteria
- all tracks from LocalStorage appear in the collection
- when LocalStorage is empty, the user gets feedback

## Complexity
Small - Medium

## Tasks
- [x] Show collection on first render
- [x] Show feedback when collection is empty
- [x] Render CollectionItems dynamically 

![0002](https://user-images.githubusercontent.com/77127212/129055133-9e09de8d-1f9b-4605-8078-eb4f569bdf59.jpg)
![0009](https://user-images.githubusercontent.com/77127212/129055136-7bcfc960-b8b6-4aa3-add1-fa60e35d4d93.jpg)
