### ISSUE TITLE
Collect Ressources

### ISSUE THREAD

**Issue by johnxgaehner** [johnxgaehner/beatmatch-buddy#2]
## Value Statement
As a developer, I want to know as much as possible about the project so that I can reach my goals in the best possible way.

## Description
Search the web for similar projects, docs to the Web Audio API and other interesting things that might help.

## Complexity
small

## Tasks
- [x] do some research
- [x] understand the Web Audio API
- [x] understand the theory of detecting tempo
