### ISSUE TITLE
Feat / Add Track To Playlist

### ISSUE THREAD

**Issue by johnxgaehner** [johnxgaehner/beatmatch-buddy#21]
## Value Statement
As a user of Beatmatch Buddy who has created a playlist, I want to be able to add tracks to those playlists so I can prepare my set etc.

## Description
The user can add a track to multiple playlists.

## Acceptance Criteria
- after clicking on the "+" next to a track, user will have the possibility to add track to one or more playlists and also remove it again

## Complexity
Large

## Tasks
- [x] Write markup for "Add To Playlist" page
- [x] Render playlist items from LocalStorage in "Add To Playlist" page
- [x] Add logic and save selection in LocalStorage
- [x] Show feedback that track is in tracklist
- [x] When track is already in playlist -> remove it

![0014](https://user-images.githubusercontent.com/77127212/129229043-51e53090-6a38-40c3-8160-666c35392bf8.jpg)
