### ISSUE TITLE
Fix / Bugs After First Sprint

### ISSUE THREAD

**Issue by johnxgaehner** [johnxgaehner/beatmatch-buddy#25]
## Value Statement
As a user of Beatmatch Buddy I don't want to have bugs so that I have the best possible experience.

## Description
Fixing a few bugs which came up during the first week.

## Acceptance Criteria
- all bugs are fixed

## Complexity
Small - Medium

## Tasks
- [x] Remove Menu Button in Home
- [x] Reset BeatCounter after Submit/Reset
- [x] Change Cancel to Reset Button
- [x] Return to previous screen after creating a playlist
- [x] Return to previous page after clicking on return
- [x] Sort playlists so they don't change position
