### ISSUE TITLE
Feat / Edit Playlists (change track order & remove tracks)

### ISSUE THREAD

**Issue by johnxgaehner** [johnxgaehner/beatmatch-buddy#27]
## Value Statement
As a user of Beatmatch Buddy I want be able to re-arrange tracks, remove them or edit new ones on the fly so my collection is always up to date.

## Description
The user will be able enter an edit mode and can order tracks by drag & drop, delete tracks, rename the playlist or even delete the whole playlist.

## Acceptance Criteria
- you can re-order by Drag & Drop
- you can delete a track from the playlist
- you can delete the whole playlist

## Complexity
Medium - Large

## Tasks
- [x] Implement an edit screen to enable all functions
- [x] Delete trackID from localstorage on Click
- [x] Delete playlistID from localstorage on Click
- [x] Implement Drag & Drop to re-order
