### ISSUE TITLE
Setup Basic Layout & Styling

### ISSUE THREAD

**Issue by johnxgaehner** [johnxgaehner/beatmatch-buddy#5]
## Value Statement
As a user of Beatmatch Buddy I want to have a landing page and be able to navigate between pages so that I can use all functionalities of the app.

## Description
Setup basic UI with header, content and navigation in footer.

## Acceptance Criteria
-  It should be responsive, working for different screen sizes (mobile first)
- The user should be able to navigate between the pages
- The header should display the title according to the page that's currently selected

## Complexity
Small

## Tasks

- [ ] Write basic markdown
- [ ] Install react-router-dom
- [ ] Define Routes and Switches

Create components for:
- [ ] Navigation
- [ ] Beat Detection
