### ISSUE TITLE
Feat / Sort Collection

### ISSUE THREAD

**Issue by johnxgaehner** [johnxgaehner/beatmatch-buddy#54]
## Value Statement
As a user of Beatmatch Buddy I want to have the best possible overview of my collection. Next to filtering and searching for tracks, I also want to sort by tempo & names.

## Description
With the help of sorting I can find the tracks I need or looking for!

## Acceptance Criteria
- I can sort by tempo, artist, track and record title
- ascending and descending order possible

## Complexity
Small - Medium

## Tasks
- [x] Write markup for Sort Feature
- [x] Toggle Menu to select Sort Type
- [x] Add logic to sort array
