### ISSUE TITLE
Setup Beat Detection

### ISSUE THREAD

**Issue by johnxgaehner** [johnxgaehner/beatmatch-buddy#6]
## Value Statement
As a user of Beatmatch Buddy I want to analyze the tempo of a given song so that can pitch it more easy and faster!

## Description
After pressing a button, the device records audio and will answer with the beat tempo of that given audio recording.

## Acceptance Criteria
- When no audio is given, the device will ask the user for action
- After clicking a button, audio will be recorded
- The tempo will be analyzed in realtime
- The tempo will be shown also after the recording is stopped

## Complexity
Large

## Tasks
- [ ] Setup Beat Detection Component
- [ ] Write basic markdown
- [ ] Import Web Audio API
- [ ] Filter & Process given/recorded audio
- [ ] Calculate tempo out of peaks in a given time
- [ ] Store result in a state
- [ ] Display tempo/state
