### ISSUE TITLE
Feat / Custom Confirm Modal Dialog

### ISSUE THREAD

**Issue by johnxgaehner** [johnxgaehner/beatmatch-buddy#70]
## Value Statement
As a developer of Beatmatch Buddy I want to customize as many components as possible so that everything fits together.

## Description
Exchanging the previously .confirm() method dialog with a self created which also could be used at different places of the app.

## Acceptance Criteria
- you can confirm & cancel the process
- when clicking outside the dialog the window disappears
- a successful deletion will be confirmed with a toast message

## Complexity
Small - Medium

## Tasks
- [x] Remove old Confirm Dialog
- [x] Write markup of custom Dialog
- [x] Add logic to Dialog
- [x] Move everything into component for re-useablity
- [x] Add custom Dialog at Delete Track + Playlist
