### ISSUE TITLE
Feat / Fetch artworks from Spotify API

### ISSUE THREAD

**Issue by johnxgaehner** [johnxgaehner/beatmatch-buddy#74]
## Value Statement
As a user of Beatmatch Buddy I want to have a nice visual feedback and find tracks without having to read but also could look through the artworks.

## Description
Tracks will be saved in collection with artwork if the track is listed in Spotify.

## Acceptance Criteria
- Tracks will be saved with artwork
- If there is no artwork, a placeholder will be shown

## Complexity
Medium

## Tasks
- [x] Do some research
- [x] Get authentication token
- [x] Write request/fetch to get artwork
- [x] Store artworkUrl in LocalStorage
- [x] Show artwork in collection
