### ISSUE TITLE
Feat / Desktop View

### ISSUE THREAD

**Issue by johnxgaehner** [johnxgaehner/beatmatch-buddy#78]
## Value Statement
As a user of Beatmatch Buddy I want to use the app not only on my mobile phone but also on larger devices.

## Description
Design will be adapted to larger screens so that Components don't reach a huge width but will be displayed in rows instead.

## Acceptance Criteria
- it looks nice!

## Complexity
Small - Medium

## Tasks
- [x] Change css flex to grid
- [x] Implement Grid on CollectionPage
- [x] Implement Grid on PlaylistsPage
- [x] Implement Grid everywhere else where necessary
